# Generated by Django 5.0.6 on 2024-07-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_App', '0002_alter_chat_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='Twitter_App.favorites', verbose_name='Избранные'),
        ),
    ]
