# Generated by Django 5.0.6 on 2024-08-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_App', '0004_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
