# Generated by Django 4.2.7 on 2024-08-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_App', '0005_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
