# Generated by Django 4.2.7 on 2024-08-14 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_App', '0009_post_comments_count_post_likes_post_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания профиля'),
        ),
    ]
