# Generated by Django 5.0.6 on 2024-08-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_App', '0010_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True, verbose_name='Ссылка'),
        ),
    ]
