# Generated by Django 5.0.6 on 2024-08-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_App', '0011_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='Twitter_App.profile'),
        ),
    ]
