# Generated by Django 5.0.6 on 2024-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_App', '0012_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='chats', to='Twitter_App.message'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='profiles',
            field=models.ManyToManyField(related_name='chats', to='Twitter_App.profile'),
        ),
    ]
