# Generated by Django 5.0.6 on 2024-08-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_App', '0013_alter_chat_messages_alter_chat_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourites',
        ),
    ]
