# Generated by Django 5.0.6 on 2024-08-28 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_App', '0018_postrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribed_by', to='Twitter_App.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='postrequest',
            unique_together={('post', 'requester')},
        ),
    ]
