# Generated by Django 5.0.6 on 2024-08-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter_App', '0019_alter_profile_subscriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribed_by', to='Twitter_App.profile'),
        ),
    ]
